# Generated by Django 4.1.2 on 2022-10-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Duenio del vehiculo'),
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo.modelo', verbose_name='Modelo del auto'),
        ),
    ]
