# Generated by Django 4.1.2 on 2022-10-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Autos'},
        ),
    ]
