# Generated by Django 4.1.2 on 2022-10-13 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto', '0003_alter_auto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Duenio del vehiculo'),
        ),
    ]
