# Generated by Django 4.1.2 on 2022-10-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.FloatField(verbose_name='Cantidad de Kilometros')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion Mantenimiento')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo del Mantenimiento')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.auto', verbose_name='Auto que esta en mantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
