# Generated by Django 4.1.2 on 2022-10-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_auto_cliente'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='auto.auto', verbose_name='Auto que esta en mantenimiento'),
        ),
    ]
